server:
  port: 8887

github:
  client:
    id: e674c1ab3b3235e81279
    secret: 45fe8abec340a15ebe6681f8b214bde4e4c8739f
  redirect:
    uri: http://localhost:8887/callback

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/community?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 5ouch5ouch
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.yiowoc.community.model