server:
  port: 8887

github:
  client:
    id: xxx
    secret: xxx
  redirect:
    uri: http://localhost:8887/callback

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/community?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: xxx
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.yiowoc.community.model
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  file:
    endpoint: xxx
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: xxx
    expires: 600000

logging:
  file:
    path: logs/
  level:
    root: info
    com.yiowoc.community.mapper: debug
  logback:
    rollingpolicy:
      max-file-size: 200MB
      max-history: 30
